---
- name: check required variables
  fail: msg="{{ item }} is not defined"
  when: item not in vars
  with_items: "{{ samba_cl_required_vars }}"

- name: check if NetworkManager is present (ALTLinux)
  command: >
    rpm -q NetworkManager-daemon
  register: networkmanager_present
  failed_when: false

- name: disable resolv.conf management by NM
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    regexp: '^dns='
    line: 'dns=none'
    backrefs: yes
    state: present
  register: nm_conf_is
  notify: restart networkmanager
  when: networkmanager_present.rc == 0

- name: Add line if not configured
  lineinfile:
    state   : present
    dest    : /etc/NetworkManager/NetworkManager.conf
    line    : 'dns=none'
    regexp  : ''
    insertafter: EOF
  when:
    - networkmanager_present.rc == 0
    - nm_conf_is.changed == false
  notify: restart networkmanager

- name: enable eth0
  lineinfile:
    path: /etc/net/ifaces/eth0/options
    regexp: '^DISABLED='
    line: 'DISABLED=no'
    backrefs: yes
    state: present
  register: net_conf_is
  changed_when: net_conf_is.changed
  notify: restart network


- meta: flush_handlers

- name: update resolver, step 1
  command: resolvconf -d NetworkManager
  when: networkmanager_present.rc == 0
  failed_when: false
  changed_when: false

- name: update resolver, step 2
  command: resolvconf -u
  changed_when: false

- name: install samba client packages
  apt_rpm:
    pkg: "{{samba_cl_packages | join(',')}}"
    state: installed
    update_cache: yes
  when: samba_cl_packages | length > 0

- name: create /etc/krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: generate initial smb.conf
  template:
    src: smb.conf.client.j2
    dest: /etc/samba/smb.conf

- name: join to the domain
  shell: system-auth write ad {{samba_realm|upper}} {{inventory_hostname_short}} {{samba_domain|upper}} 'Administrator' '{{samba_admin_pass}}'

- name: register node in localhost hostvars
  set_fact:
    samba_clients: "{{ hostvars['localhost']['samba_clients'] | default([]) }} + [ '{{ inventory_hostname_short }}' ]"
  delegate_to: localhost
  delegate_facts: true
