---
- block:
  - name: check required variables
    fail: msg="{{ item }} is not defined"
    when: item not in vars
    with_items: "{{ samba_dc_required_vars }}"

  - name: install samba DC common packages
    apt_rpm:
      pkg: "{{samba_dc_common_packages | join(',')}}"
      state: installed
      update_cache: yes
    when: (samba_dc_common_packages | length > 0) and samba_flavor != 'client'
    notify: restart samba

  - name: create /etc/krb5.conf
    template:
      src: krb5.conf.j2
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: 0644

  - name: set hostname (non permanent)
    shell: hostname "{{inventory_hostname_short}}.{{samba_realm}}"
    changed_when: false

  - name: purge other resolv.conf`s
    shell: |
      find /etc/net/ifaces/*/resolv.conf -rm
    register: res
    changed when: res.rc == 0
    failed_when: false

  - name: set master as an only nameserver
    template:
      src: resolv.conf.j2
      dest: /etc/net/ifaces/lo/resolv.conf

  - name: black magick
    shell: update_chrooted all
    changed_when: false

  - name: restart network service
    service:
      name: network
      state: restarted
  when: samba_flavor != 'gen_test_env'

- name: deploy DC master
  include_tasks: master.yml
  when: samba_flavor == 'master'

- name: deploy DC replica
  include_tasks: replica.yml
  when: samba_flavor == 'replica'

- name: deploy samba client
  include_tasks: client.yml
  when: samba_flavor == 'client'

- name: refresh kerberos key
  shell: echo {{samba_admin_pass}} | kinit administrator@{{samba_realm|upper}}
  changed_when: false
  register: task_result
  until: task_result.rc == 0
  retries: 30
  delay: 1

- name: restart samba service
  service:
    name: samba
    state: restarted
  when: samba_flavor != 'client'

- name: generate test env vars
  include_tasks: generate_test_env_vars.yml
  when: samba_flavor == 'gen_test_env'
