---
- name: remove conflict samba server packages
  shell: "apt-get remove -y nss-ldapd nscd"

- name: Stop BIND9 daemon
  service:
    name: bind
    enabled: false
    state: stopped
  register: cmd_result
  failed_when: "cmd_result is failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

- name: Stop Kerberos V5 KDC if already started
  service:
    name: krb5kdc
    enabled: false
    state: stopped
  register: cmd_result
  failed_when: "cmd_result is failed  and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

- name: Stop Kerberos V5 Admin server if already started
  service:
    name: kadmin
    enabled: false
    state: stopped
  register: cmd_result
  failed_when: "cmd_result is failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

- name: Stop Kerberos V5 replica KDC update server if already started
  service:
    name: kpropd
    enabled: false
    state: stopped
  register: cmd_result
  failed_when: "cmd_result is failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

- name: Stop Samba DC if already started
  service:
    name: samba
    state: stopped
  register: cmd_result
  failed_when: "cmd_result is failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

- name: Stop Samba fileserver if already started
  service:
    name: smb
    enabled: false
    state: stopped
  register: cmd_result
  failed_when: "cmd_result is failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

- name: Stop Samba NetBIOS over IP if already started
  service:
    name: nmb
    enabled: false
    state: stopped
  register: cmd_result
  failed_when: "cmd_result is failed and ('find' not in cmd_result.msg and 'found' not in cmd_result.msg)"

- name: Check if conflicting processes are running
  shell: |
    lsof -i UDP:53 -i TCP:445 -i TCP:389 -i UDP:88 -F f | grep ^p | sed 's/^p//' | uniq
  register: conflict_processes

- name: Stop conflicting services
  shell: "kill {{ item }}"
  with_items: "{{ conflict_processes.stdout_lines }}"
